### PR TITLE
Check if auth-minimum-user-id is already set to zero on rootless

### LINKED ISSUE #653: Rootless support: rserver.conf compatibility minor issue in authorization check
### Container image name

rocker/ml-verse:4.3.0

### Container image digest

rocker/ml-verse@sha256:6673a533b6f1e845ed017ebd4236a7fe3fc2436980080531a0e4f5b19ed8474b

### What operating system are you seeing the problem on?

Linux

### System information

podman:  3.4.2
Ubuntu: 22.04

### Bug description

In my (rootless) setup, image preparation already set `auth-minimum-user-id = 0` in `/etc/rstudio/rserver.conf`

This is now reported as error:

```
minimum authorised user already exists in /etc/rstudio/rserver.conf: 0
RUNROOTLESS=true mode requires setting minimum authorised user to 0. Exiting
```

Proposed update:

In [init_userconf.sh#L124](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/init_userconf.sh#L124)

the test can check if root is already enabled:

```
if [ "${RUNROOTLESS}" = "true" ]; then
# ---[change: begin]-----------------------------------------------------------------------------------------------
  check_user_id=$(grep -F "auth-minimum-user-id" /etc/rstudio/rserver.conf | sed -e "s/^.*= *//")
  if [[ "$check_user_id" = '0' ]]; then
     echo "root user already authorized in /etc/rstudio/rserver.conf: $check_user_id, not changed"
  elif [[ -n $check_user_id ]]; then
# ---[change: end]-----------------------------------------------------------------------------------------------
        echo "minimum authorised user already exists in /etc/rstudio/rserver.conf: $check_user_id"
        echo "RUNROOTLESS=true mode requires setting minimum authorised user to 0. Exiting"
        exit 1
    else
        echo "setting minimum authorised user to 0 (RUNROOTLESS=true)"
        echo auth-minimum-user-id=0 >>/etc/rstudio/rserver.conf
    fi
elif [ "$USERID" -lt 1000 ]; then # Probably a macOS user, https://github.com/rocker-org/rocker/issues/205
    echo "$USERID is less than 1000"
    check_user_id=$(grep -F "auth-minimum-user-id" /etc/rstudio/rserver.conf)
    if [[ -n $check_user_id ]]; then
        echo "minimum authorised user already exists in /etc/rstudio/rserver.conf: $check_user_id"
    else
        echo "setting minimum authorised user to 499"
        echo auth-minimum-user-id=499 >>/etc/rstudio/rserver.conf
    fi
fi

```

### How to reproduce this bug?

```sh
Build an image with `auth-minimum-user-id = 0` in `/etc/rstudio/rserver.conf`
```

### PR DESCRIPTION
**Pull request by zeehio**
Closes #653

The patch does some minimal grep/sed parsing of `/etc/rstudio/rserver.conf`, which may not be super robust, but good and simple enough for our use case

### CODE REVIEW

File: scripts/init_userconf.sh [hunk 1]
```diff
@@ -122,8 +122,10 @@ elif [ -z "$PASSWORD" ]; then
 fi
 
 if [ "${RUNROOTLESS}" = "true" ]; then
-    check_user_id=$(grep -F "auth-minimum-user-id" /etc/rstudio/rserver.conf)
-    if [[ -n $check_user_id ]]; then
+    check_user_id=$(grep -F "auth-minimum-user-id" /etc/rstudio/rserver.conf | sed -e "s/^.*= *//")
```
Comment (eitsupi) [inline scripts/init_userconf.sh:125]:
```suggestion
    check_user_id="$(grep -F auth-minimum-user-id /etc/rstudio/rserver.conf | sed -e 's/^.*= *//')"
```

File: scripts/init_userconf.sh [hunk 2]
```diff
@@ -122,8 +122,10 @@ elif [ -z "$PASSWORD" ]; then
...
+    if [[ "$check_user_id" = '0' ]]; then
```
Comment (eitsupi) [inline scripts/init_userconf.sh:126]:
```suggestion
    if [[ "$check_user_id" = "0" ]]; then
```

**Review by eitsupi — COMMENTED** [review]
Thanks for working on this!

A few comments.

**Comment by zeehio** [comment]
> Thanks for working on this!
> 
> A few comments.

Thanks for your quick review!

**Comment by eitsupi** [comment]
@cboettig Cloud you take a look at this?

**Comment by cboettig** [comment]
yup, this looks good to me! Merge when ready.

**Comment by eitsupi** [comment]
Ok, thanks.
Let's merge this for now since the next build is scheduled tomorrow (due to the new R version)
